package com.aiwazian.messenger.utils

object Route {
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val LOGOUT = "logout"
    const val FIND_USER_BY_LOGIN = "findUserByLogin/{login}"
    const val ME = "me"
    const val SEARCH_USER = "searchUser"
    const val GE_USER_BY_ID = "user/{id}"
    const val PROFILE_UPDATE = "profileUpdate"
    const val CHATS = "chats"
    const val UNARCHIVED_CHATS = "unarchivedChat"
    const val ARCHIVED_CHATS = "archivedChat"
    const val PIN_CHAT = "pinChat"
    const val UNPIN_CHAT = "unpinChat"
    const val GET_SESSIONS = "sessions"
    const val TERMINATE_SESSION = "session/{id}"
    const val UPDATE_FCM_TOKEN = "updateFcmToken"
    const val TERMINATE_ALL_SESSIONS = "terminateAllSessions"
    const val GET_DEVICE_COUNT = "sessionCount"
    const val DELETE_CHAT = "deleteChat"
    const val MESSAGES = "messages"
    const val ADD_CHAT_TO_ARCHIVE = "addChatToArchive"
    const val DELETE_CHAT_FROM_ARCHIVE = "deleteChatFromArchive"
    const val SEND_MESSAGE = "message"
    const val FOLDER = "folder"
    const val FOLDERS = "folders"
    const val DELETE_FOLDER = "folder/{id}"
    const val GET_FOLDER_CHATS = "folder/{id}/chats"
}