package com.aiwazian.messenger.utils

object Route {
    const val ME = "me"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val LOGOUT = "logout"
    const val FIND_USER_BY_LOGIN = "findUserByLogin/{login}"
    const val SEARCH_USER = "searchUser"
    const val GE_USER_BY_ID = "user/{id}"
    const val CHECK_USERNAME = "checkUsername/{username}"
    const val SAVE_USERNAME = "me/username/{username}"
    const val PROFILE_UPDATE = "profileUpdate"
    const val ARCHIVED_CHATS = "archivedChat"
    const val UNARCHIVED_CHATS = "unarchivedChat"
    const val GET_SESSIONS = "sessions"
    const val TERMINATE_SESSION = "session/{id}"
    const val GET_DEVICE_COUNT = "sessionCount"
    const val UPDATE_FCM_TOKEN = "updateFcmToken"
    const val TERMINATE_ALL_SESSIONS = "terminateAllSessions"
    const val CHANGE_CLOUD_PASSWORD = "changeCloudPassword"
    const val CHATS = "chats"
    const val CHAT_MESSAGES = "chat/{id}/messages"
    const val GET_CHAT_LAST_MESSAGE = "chat/{chatId}/messages/last"
    const val DELETE_CHAT = "chat/{id}"
    const val GET_CHAT_INFO = "chat/{id}"
    const val PIN_CHAT = "chat/{id}/pin"
    const val UNPIN_CHAT = "chat/{id}/pin"
    const val ADD_CHAT_TO_ARCHIVE = "chat/{id}/archive"
    const val DELETE_CHAT_FROM_ARCHIVE = "chat/{id}/archive"
    const val SEND_MESSAGE = "message"
    const val DELETE_MESSAGE = "chat/{chatId}/messages/{messageId}"
    const val MAKE_AS_READ_MESSAGE = "chat/{chatId}/messages"
    /** Folder **/
    const val FOLDER = "folder"
    const val FOLDERS = "folders"
    const val DELETE_FOLDER = "folder/{id}"
    const val PIN_CHAT_IN_FOLDER = "folders/{folderId}/chats/{chatId}/pin"
    const val UNPIN_CHAT_IN_FOLDER = "folders/{folderId}/chats/{chatId}/pin"
    const val GET_MY_PRIVACY = "me/privacy"
    const val CHANGE_BIO_PRIVACY = "userPrivacy/bio/{value}"
    const val CHANGE_DATE_OF_BIRTH_PRIVACY = "userPrivacy/dateOfBirth/{value}"
}